// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fabriciolfj/register-product-go/controller"
	"github.com/fabriciolfj/register-product-go/datasource"
	"github.com/fabriciolfj/register-product-go/repository"
	"github.com/fabriciolfj/register-product-go/service"
)

// Injectors from wire.go:

func InitializeProductControllerWire() (*controller.ProductController, error) {
	db := datasource.NewDataBase()
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controller.NewProductController(productService)
	return productController, nil
}
